name: Accessibility Check

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    accessibility:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: yarn
            
            - name: Install node modules
              run: yarn install --immutable

            - name: Build application
              run: yarn build

            - name: Run accessibility checks
              run: yarn a11y:check