name: Accessibility Check

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    accessibility:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install node modules
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Start application
              run: npm run start
              env:
                NODE_ENV: production

            - name: Wait for application
              run: sleep 10s
              shell: bash

            - name: Run accessibility checks
              run: npm run a11y:check